# 1表示开启调试，会加载大地图用于展示，速度稍慢
debug_enable: 1

# 地图资源路径
resource_path: 'G:\PyCharmProgram\minimap\minimap\resources'

# 点位资源路径
points_path: 'G:\PyCharmProgram\minimap\minimap\resources\pathlist'
#points_path: 'G:\PyCharmProgram\pyinstallerdemo1\pyinstallertest\dist\minimap\_internal\resources\pathlist'

########################## 地图配置 #############################
# 中心点设置璃月天衡山右边那个十字圆环
center_x: 19689.298
center_y: 13528.16
window_name: '原神'  # 游戏窗口名称

# [重要选项] 建议1024或者2048
# 指的是小地图在多大的局部区域内搜索，区域越大，单次请求的性能开销越大，但是在一定范围内可以减少全局匹配的次数
# 如果你需要在大范围内移动，为了减少全局匹配次数，可以设置稍微大一点的值
# 参考速度:
# 1024 |  2048 | 4096 |
# 0.03,  0.04   0.07
local_map_size: 1024 # 允许范围512 ~ 4096 # 越大越卡


##########################路径执行器配置#############################
show_path_viewer: 1  # 跑点位的时候是否展示路径
path_viewer_width: 500  # 路径展示的宽高，允许范围(50~4096
# 自动拾取开关(没有做ocr，仅是在接近点位的时候疯狂按下f)
enable_crazy_f: 0
# 移动到下一个点位最大允许时间（秒），超过该时间则跳过该点位, 允许范围(5~60)
# 注意游泳模式下产生的位移距离较小，可能更容易触发超时异常
move_next_point_allow_max_time: 20
# 8秒内移动的总距离(像素)在多少范围内认为卡住，允许范围(2~50)
stuck_movement_threshold: 20

# 对于目标点精确到多少个像素认为接近, 允许范围(1~10) 目前没有那么高静定，建议 > 1,否则可能原地打转
target_nearby_threshold: 2
# 对于途径点精确到多少个像素认为接近, 允许范围(2~50)
path_point_nearby_threshold: 5  # 对于途径点精确度奥多少个像素认为接近

# 是否允许小碎步接近目标：注意此选项对Point.type=='path'的途径点以及游泳模式下无效
# 人物原地打转时，会强制临时启用小碎步
allow_small_steps: 1

# 死亡后，是否允许使用道具复苏角色
enable_food_revive: 1

# 跑路的时候不断按下按键（例如e技能开盾，z也可以装砍树的道具) 0表示关闭,1表示开启
enable_loop_press_e: 0
enable_loop_press_z: 0
enable_loop_jump: 0
loop_press_interval: 0.1  # 循环按下e的时间间隔
small_step_interval: 0.1 # 小碎步松开w的频率,允许范围(0.02~0.2)
# 是否允许途径点冲刺
enable_dash: 1

# 转向速度,允许范围200~800, 值越大转向越快
change_rotation_max_speed: 1000

# 多少秒更新一次位置(允许值0.01~0.2)
update_user_status_interval: 0.05

#在跑路的过程中,角色'当前位置'和走过的'历史点位中最近存放的一个点位'差距超过多少的时候认为产生了位置突变
# 位置突变用于判定角色死亡后被传送到了较远的锚点情况.
# 允许范围(50-200)
position_mutation_threshold: 50

# 一段路径中允许位置突变次数: 超过传送次数则停止执行,允许范围(0~10)
position_mutation_max_time: 2

# 路径突变后,会执行搜索最近点位策略,最近点要求低于多少距离, 范围(80, 500)
search_closet_point_max_distance: 200

# 无服务器模式, 开启后,执行BasePathExecutors无需开启OCRServer和MinimapServer服务器, 但是启动速度会很慢
enable_serve_less_mode: 0
############################ 传送配置 ##############################



############################ 战斗配置 ##############################

# 注意！文件名称必须按照游戏内队伍顺序书写否则无法切人，并且每个队员用下划线分割
# 括号内容是游戏内队伍的自定义简称，以后切队伍可能用到。
# default_fight_team: '那维莱特_莱伊拉_行秋_枫原万叶(龙莱行万).txt'
default_fight_team: '钟离_芙宁娜_枫原万叶_流浪者_(钟芙万流).txt'
fight_duration: 15  # 战斗持续时长,允许范围1~1000秒


############################ 委托配置 ##############################

# 每日委托总计最长执行时间，允许范围(60~3600)秒
daily_task_execute_timeout: 1000
# 每日委托单次战斗最长执行时间，允许范围(10~400)秒
daily_task_fight_timeout: 40
# 每日委托破坏单个柱子(攀高危险)最长执行时间，允许范围(10~400)秒
daily_task_destroy_timeout: 20



############################ 地脉配置 ##############################

# 地脉总计最长执行时间，允许范围(60~3600)秒
leyline_outcrop_task_execute_timeout: 1000
# 地脉单次战斗最长执行时间，允许范围(10~400)秒
leyline_outcrop_task_fight_timeout: 40



############################ 服务器配置 #############################
minimap:
  # 一定要设置为127.0.0.1而不是localhost，否则速度可能会很慢
  host: 127.0.0.1
  port: 5000
ocr:
  host: 127.0.0.1
  port: 5000
