########################## 地图配置 #############################
# 中心点设置璃月天衡山右边那个十字圆环
#center_x: 19689.298
#center_y: 13528.16
'璃月':
  img_name: 'liyue'
  center: [5380, 7384]  # 禁止修改, 璃月天衡山右边那个十字圆环
  version: 0
  width: 8495
  height: 8585
'蒙德':
  img_name: 'mengde'
  sigma: 1.4  # sift参数
  center: [427, 7359]  # 该图左上角坐标与璃月中心点坐标的偏差
  version: 0
  width: 6994
  height: 5465
'稻妻':
  img_name: 'daoqi'
  center: [-1080, -2096]   # 该图左上角坐标与璃月中心点坐标的偏差
  version: 0
  width: 9895
  height: 10624
'须弥':
  img_name: 'xumi'
  center: [13797, 5174]   # 该图左上角坐标与璃月中心点坐标的偏差
  version: 0
  width: 11336
  height: 11786
'枫丹':
  img_name: 'fengdan'
  center: [10802, 12505] # 该图左上角坐标与璃月中心点坐标的偏差
  version: 0
  width: 6735
  height: 9386
'纳塔':
  img_name: 'nata'
  center: [20884, 2323]  # 该图左上角坐标与璃月中心点坐标的偏差
  version: 0
  width: 9034
  height: 8117
'层岩巨渊':
  img_name: 'juyuan'
  center: [0, 0]  # 独立地图
  version: 0
  width: 2024
  height: 1722

'渊下宫':
  # 注意：渊下宫三个隐藏地图匹配质量不好，调整sift参数无果，考虑放弃
  img_name: 'yuanxiagong'
  center: [0, 0]    # 独立地图
  version: 0
  width: 3321
  height: 3305