# 1表示开启调试，会加载大地图用于展示，速度稍慢
debug_enable: 1

# 地图资源路径
resource_path: 'G:\PyCharmProgram\minimap\minimap\resources'

# 点位资源路径
points_path: 'G:\PyCharmProgram\minimap\minimap\autotrack\pathlist\甜甜花'

########################## 地图配置 #############################
# 中心点设置璃月天衡山右边那个十字圆环
center_x: 15593.298
center_y: 13528.16
window_name: '原神'  # 游戏窗口名称

# [重要选项] 建议1024或者2048
# 指的是小地图在多大的局部区域内搜索，区域越大，单次请求的性能开销越大，但是在一定范围内可以减少全局匹配的次数
# 如果你需要在大范围内移动，为了减少全局匹配次数，可以设置稍微大一点的值
local_map_size: 1024  # 允许范围512 ~ 10240


##########################路径执行器配置#############################
show_path_viewer: 1  # 跑点位的时候是否展示路径
path_viewer_width: 500  # 路径展示的宽高，允许范围(50~4096)
# 自动拾取开关(没有做ocr，仅是在接近点位的时候疯狂按下f)
enable_crazy_f: 0
# 移动到下一个点位最大允许时间（秒），超过该时间则跳过该点位, 允许范围(5~60)
move_next_point_allow_max_time: 20
# 8秒内移动的总距离(像素)在多少范围内认为卡住，允许范围(2~50)
stuck_movement_threshold: 20

# 对于目标点精确到多少个像素认为接近, 允许范围(0.1~10) 目前没有那么高静定，建议 > 1,否则可能原地打转
target_nearby_threshold: 2
# 对于途径点精确到多少个像素认为接近, 允许范围(2~50)
path_point_nearby_threshold: 8  # 对于途径点精确度奥多少个像素认为接近

# 是否在接近非途径点的时候，使用小碎步
allow_small_steps: 1

# 跑路的时候不断按下按键（例如e技能开盾，z也可以装砍树的道具)
enable_loop_press_e: 0
enable_loop_press_z: 0
enable_loop_jump: 0

# 是否允许途径点冲刺
enable_dash: 1

############################ 传送配置 ##############################



############################ 服务器配置 #############################
minimap:
  # 一定要设置为127.0.0.1而不是localhost，否则速度可能会很慢
  host: 127.0.0.1
  port: 5000
ocr:
  host: 127.0.0.1
  port: 5001
